import Head from 'next/head'
import Image from 'next/image'
// import * as basicScroll from 'basicscroll'

// import styles from '../styles/Home.module.css';
import Layout from '../Components/UI/Layout';
import HomePage from '../Components/HomePage';
import AboutUs from '../Components/AboutUs';
import FAQs from '../Components/UI/FAQs';
import Cc from '../Components/UI/CC';
// import { useEffect } from 'react';
import Footer from '../Components/UI/Footer';

export default function Home() {

  useEffect(() => {

    document.querySelectorAll(".scene").forEach(elem => {
      const modifier = elem.getAttribute("data-modifier");

      basicScroll.
        create({
          elem: elem,
          from: 0,
          to: 519,
          direct: true,
          props: {
            "--translateY": {
              from: "0",
              to: `${25 * modifier}px`
            }
          }
        }).start();
    });
  }, [])

  return (
    <>
      <Head>
        <title> Team Vibhav</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico?" />
      </Head>
      <main>

        <Layout>

       
            <div >
            <Image src="/assets/4x/5@4x.png" className="scene" data-modifier="10"  width={7681} height={7921}   ></Image>
            <Image src="/assets/4x/4@4x.png" className="scene" data-modifier="8"  width={7681} height={7921}   ></Image>
            <Image src="/assets/4x/3@4x.png"className="scene" data-modifier="6"  width={7681} height={7921}   ></Image>
            <Image src="/assets/4x/2@4x.png" className="scene" data-modifier="4"  width={7681} height={7921}   ></Image>
            <Image src="/assets/4x/1@4x.png" className="scene" data-modifier="2"  width={7681} height={7921}   ></Image>
          </div>



            <div className='z-50 flex flex-col'>


              <HomePage />
              <AboutUs />
              <Cc />
              <FAQs />
              <Footer/>
          </div>
        </Layout>
      </main>
    </>
  )
}





     {/* <img className="scene" data-modifier="10" src="https://s.electerious.com/parallaxscene/p0.png" />
            <img className="scene" data-modifier="18" src="https://s.electerious.com/parallaxscene/p1.png" />
            <img className="scene" data-modifier="12" src="https://s.electerious.com/parallaxscene/p2.png" />
            <img className="scene" data-modifier="8" src="https://s.electerious.com/parallaxscene/p3.png" />
            <img className="scene" data-modifier="6" src="https://s.electerious.com/parallaxscene/p4.png" />
            <img className="scene" data-modifier="0" src="https://s.electerious.com/parallaxscene/p6.png" />
             */}